version: '3.4'

services:
  cursesapi:
   container_name: cursesapi
   environment:
    - ASPNETCORE_ENVIRONMENT=Development
   ports:
    - "5010:80"

  studentsapi:
   container_name: studentsapi
   environment:
    - ASPNETCORE_ENVIRONMENT=Development
   ports:
    - "5090:80"

  getaway:
    container_name: getaway
    environment:
        - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "1088:80"

  sqldata:
   container_name: sqldata
   environment:
    SA_PASSWORD: "My!P@ssw0rd1"
    ACCEPT_EULA: "Y"
   ports:
     - "1433:1433"